trailingComma = "es5"
printWidth = 120
tabWidth = 4
semi = false
quoteProps = "consistent"

plugins = ["@trivago/prettier-plugin-sort-imports"]

importOrder = ["^node:", "^react$", "^next", "<THIRD_PARTY_MODULES>", "^[./]"]
importOrderSeparation = false
importOrderSortSpecifiers = true
