# Generated by Django 2.1.1 on 2018-10-09 20:10

# pylint: skip-file

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GutenbergRawData",
            fields=[
                (
                    "gutenberg_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("rdf_content", models.TextField()),
                ("assets", django.contrib.postgres.fields.jsonb.JSONField()),
                ("intro", models.TextField(null=True)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "gutenberg_raw_data"},
        )
    ]
